# Ingress para exponer todos los microservicios
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservicios-ingress
  namespace: microservicios
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /clientes
        pathType: Prefix
        backend:
          service:
            name: ms-clientes-service
            port:
              number: 8081
      - path: /tickets
        pathType: Prefix
        backend:
          service:
            name: ms-tickets-service
            port:
              number: 4000
      - path: /notificaciones
        pathType: Prefix
        backend:
          service:
            name: notificacion-service
            port:
              number: 3000
      - path: /zones
        pathType: Prefix
        backend:
          service:
            name: zone-core-service
            port:
              number: 8080
